name: MCPlanes
version: 0.0.0
main: co.tantleffbeef.mcplanes.Plugin
api-version: 1.19

depend: [ProtocolLib]

permissions:
  mcplanes.resourcegive:
    default: op

commands:
  resourcegive:
    description: "gives a custom item"
    aliases:
      - rg
      - planegive
      - pgive
      - rgive
    usage: "Usage: /resourcegive <player> <item id>"
    permission: mcplanes.resourcegive

#libraries:
#  - me.lucko:commodore:2.2
