# MCPlanes config

resource-pack: true

# The web address to bind to
webserver-bind: "0.0.0.0"
# The web address clients actual connect to
webserver-url: "127.0.0.1"

webserver-port: 8467

# whether to include and register mcplanes items
mcplanes-items: true

crafting:
  allow-crafting: true
  unlock-recipes: true
