name: MCPlanes
version: 0.0.2
main: co.tantleffbeef.mcplanes.McPlanes
api-version: "1.20"

authors: [gIsForGravity, Finnerex, SniperNerd]

depend: [ProtocolLib]

permissions:
  mcplanes.resourcegive:
    default: op
  mcplanes.testing:
    default: op

commands:
  resourcegive:
    description: "gives a custom item"
    aliases:
      - rg
      - planegive
      - pgive
      - rgive
    usage: "Usage: /resourcegive <player> <item id>"
    permission: mcplanes.resourcegive
#  vehiclesummon:
#    description: "summons a vehicle"
#    aliases:
#      - vs
#      - vsummon
#      - psummon
#    usage: "Usage: /vehiclesummon <vehicle_id>"
  p51:
    description: "summons a p51"
    permission: mcplanes.testing
  ride:
    description: "rides the p51"
    permission: mcplanes.testing
  mcpdebug:
    description: "runs whatever code I set it to run"
    permission: mcplanes.testing
  deletecurrent:
    description: "deletes the last p51"
    permission: mcplanes.testing
  applyforce:
    description: "applies a force to the last p51"
    permission: mcplanes.testing

# libraries:
#   - org.eclipse.jetty:jetty-server:11.0.14
